### ISSUE TITLE
Make the docs generation more flexible, consider supporting a template

### ISSUE THREAD

**Issue by simonbasle** [micrometer-metrics/micrometer-docs-generator#22]
A templating engine like thymeleaf could make the docs generation more flexible, especially with the current hardcoded aspects like the introductory paragraph, the format (sections vs tables), the "enclosing class: ???" mention on each meter, etc...

A single template could be enough if there is support for iterating over multiple template inputs.

This would imply copy-pasting the original template if one only wants to modify a single aspect of the rendering, but that should be acceptable if said template is easily available.

**Comment by ttddyy** [comment]
The 1a0193419d88c7f56a8305a54211842bd53b74d0 converted the hardcoded strings in `toString()` to handlebars templates. (templates files [here](https://github.com/micrometer-metrics/micrometer-docs-generator/tree/main/micrometer-docs-generator/src/main/resources/templates))
Then, 71f9fa830bb18106271847fbcad2fad2229b9413 added a new module `micrometer-docs-generator` which now has [options to specify template files](https://github.com/micrometer-metrics/micrometer-docs-generator/commit/660a2560568f2a0004f3463f23fbe2cde0e0f7fc).
The migration doc is [here](https://github.com/micrometer-metrics/micrometer-docs-generator/wiki/1.0.0-Migration-Guide).
