### ISSUE TITLE
Make a doc generator as OS-independent

### ISSUE THREAD

**Issue by artembilan** [micrometer-metrics/micrometer-docs-generator#33]
Right now it looks like generated docs comes with a Linux line separator.
It would be great if generated docs would use a `System.lineSeparator()` instead of hard-coded `\n`.
This is a screenshot of commit message to confirm:
![image](https://user-images.githubusercontent.com/1071590/192557637-ff81a65f-bb0b-49ca-8633-7b5bda25daa5.png)

NOTE: The conversion from Windows line separator is done on commit either way.
It is only the problem during development, when these files are regenerated but without changes.

**Comment by ttddyy** [comment]
In RC1, file generation has changed to use a handlebar template rather than `toString()` from internal classes.
I don't have a windows, so I cannot test it but can you try with the latest snapshot (OR even RC1)? As far as quick intellij search, there is no `\n` used in the current code base.

**Comment by artembilan** [comment]
Thank you @ttddyy , for looking into this.
No, it still generates them with an `LF` symbol.
In the end I do this though:
```
task filterMetricsDocsContent(type: Copy) {
	dependsOn generateObservabilityDocs
	from generatedDocsDir
	include '_*.adoc'
	into generatedDocsDir
	rename { filename -> filename.replace '_', '' }
	filter { line -> line.replaceAll('org.springframework.integration', 'o.s.i') }
}
```
which creates for me new edited files and those are already created with a proper `CRLF` symbol.

Technically I don't care about generated files right now since I don't push them into the repo, but rather they are used as a resource for the target docs (HTML, PDF) generation alongside with my existing `adoc` content.
So, from big height we can just ignore this or close altogether to avoid extra noise in backlog. 
But it would be great if that Handlebars can output result in OS-dependent line separator instead of the one compiled into jar with those templates.

**Comment by ttddyy** [comment]
@artembilan I have updated the code to replace the line delimiter while loading the template files.
This would replace the one in template file to the one used by the running OS by `System.lineSeparator()`.
So, it should be replacing `LF` to `CRLF` on windows.

Please try the latest snapshot.

**Comment by artembilan** [comment]
That works.

Thank you, @ttddyy !

Fixed via: https://github.com/micrometer-metrics/micrometer-docs-generator/commit/c9ec96279bcbe3bb599bc436302fe266c4a1fdbd
