### ISSUE TITLE
Consider to extract a contextClassName from a super interfaces of the ObservationConvention impls

### ISSUE THREAD

**Issue by artembilan** [micrometer-metrics/micrometer-docs-generator#36]
Right now the logic is like this:
```
                if (myClass instanceof JavaClassImpl) {
                    Pattern classPattern = Pattern.compile("^.*ObservationConvention<(.*)>$");
                    JavaClassImpl holder = (JavaClassImpl) myClass;
                    for (String anInterface : holder.getInterfaces()) {
                        if (isGlobalObservationConvention(anInterface)) {
                            this.observationConventionEntries.add(new ObservationConventionEntry(unit.getGoverningType().getCanonicalName(), ObservationConventionEntry.Type.GLOBAL, contextClassName(classPattern, anInterface)));
                        } else if (isLocalObservationConvention(anInterface)) {
                            this.observationConventionEntries.add(new ObservationConventionEntry(unit.getGoverningType().getCanonicalName(), ObservationConventionEntry.Type.LOCAL, contextClassName(classPattern, anInterface)));
                        }
                    }
                    return FileVisitResult.CONTINUE;
                }
```

So, this assumes that our custom `ObservationConvention` does just exactly `implements ObservationConvention<CustomContext>`, when real use-cases is like this:
```
public class DefaultMessageReceiverObservationConvention implements MessageReceiverObservationConvention {
...
}
public interface MessageReceiverObservationConvention extends ObservationConvention<MessageReceiverContext> {
```

Our point is make end-users life easier in providing custom conventions into our components. Therefore we expose a specific interface.

Therefore this request is to see if the current parser is able to dig deeper in the class hierarchy to to find its desired pattern for a generic argument to extract.

**Comment by ttddyy** [comment]
Hi @artembilan 

I have rewrote the search algorithm and updated the `ObservationConvention` detection in 4838a1d4e3778faf2118d8ff05efb40ff79587fa and a31989bfedb52134ccc31b7424ed5caaed8bb77d
The latest snapshot will look for the nested and parent classes/interfaces hierarchy as well.

I checked with spring-integration.

Comparing the generated `_conventions.adoc` with RC1 and current snapshot:

```
> diff _conventions.adoc-RC1 _conventions.adoc-SNAPSHOT
9c9
< |`org.springframework.integration.support.management.observation.DefaultMessageReceiverObservationConvention`|`n/a`
---
> |`org.springframework.integration.support.management.observation.DefaultMessageReceiverObservationConvention`|`MessageReceiverContext`
```

It now detected the `MessageReceiverContext` for the convention class from parent `MessageReceiverObservationConvention.java`.
