### ISSUE TITLE
Link to an example of the docs generated

### ISSUE THREAD

**Issue by vab2048** [micrometer-metrics/micrometer-docs-generator#96]
Is there an example which can be linked to in order to show what is currently generated by this project?

Perhaps linking it to https://github.com/jonatan-ivanov/teahouse?

**Comment by ttddyy** [comment]
You can find these reference docs use generated adocs on the linked sections:

- [reactor-netty](https://projectreactor.io/docs/netty/release/reference/index.html#_observability)
- [reactor](https://projectreactor.io/docs/core/release/reference/#_meters_and_tags_for_reactor_core_micrometer_module)
- [datasource-micrometer](https://jdbc-observations.github.io/datasource-micrometer/docs/current/docs/html/#appendix-observability-metrics-and-spans)

**Comment by jonatan-ivanov** [comment]
Also, you can see the docs of docs-gen here: https://micrometer.io/docs/observation#_documentation_generation

And in addition what Tadaya mentioned, Spring Cloud Task also generates docs using it: https://docs.spring.io/spring-cloud-task/docs/current/reference/html/#observability
